### ISSUE TITLE
The plugin does not work in Flutter Web

### ISSUE THREAD

**Issue by patricknicolosi** [point-source/dart_ping#1]
![Cattura](https://user-images.githubusercontent.com/23001470/109058835-c59d3480-76e3-11eb-92ef-d850b062569c.PNG)

**Comment by point-source** [comment]
Correct. I need to figure out how to prevent the analyzer from incorrectly determining that it supports web. As far as I know, web browsers do not have appropriate system access necessary to ping a network device. Not sure web support is possible in this case.

**Comment by patricknicolosi** [comment]
Doesn't work for desktop flutter on Windows and Dart native application. It returns no results when running the sample code on these platforms.


![ezgif-1-524ec8190941](https://user-images.githubusercontent.com/23001470/109382055-5b9caf00-78de-11eb-88a8-08578163c27c.gif)


The string "******" is printed in the GIF and no ping results.

**Comment by point-source** [comment]
I have created a new issue (#2) for your second report. As for the first, that has now been corrected so I'm closing this issue
