### ISSUE TITLE
Setting EN locale before performing ping

### ISSUE THREAD

**Issue by marchellodev** [point-source/dart_ping#11]
Hey, as far as I understand, this plugin won't work if user's OS language is not English. I have only encountered this on Windows and Linux though, mac and mobiles seems to work just fine.

To bypass that I suggest setting the shell language to English and then executing the ping command.
Windows: `chcp 437`
Linux: `export LC_ALL=C`

**Comment by point-source** [comment]
Great suggestion. Will implement this tomorrow. Thanks!

**Comment by point-source** [comment]
I have added basic support for this in 6.1.0 (released today). Let me know if it works for you.
