### ISSUE TITLE
Android support? 

### ISSUE THREAD

**Issue by amroshahbari27** [point-source/dart_ping#14]
is there any Android support ? because it just doesn't work ... 
for instance : 

Ping('google.com',count: 1,timeout:1) === > PingSummary(transmitted:1, received:0), time: 0 ms, Errors: [NoReply]

Ping('google.com',count: 3,timeout:3) ===>
I/flutter ( 9083): PingError(response:PingResponse(seq:1), error:RequestTimedOut)
I/flutter ( 9083): PingError(response:PingResponse(seq:2), error:RequestTimedOut)
I/flutter ( 9083): PingSummary(transmitted:3, received:0), time: 2032 ms, Errors: [RequestTimedOut, RequestTimedOut, NoReply]

**Comment by point-source** [comment]
Yes. Android is supported. I will test it again to make sure it's still working. Have you tried pinging manually with a terminal emulator on your phone just to make sure that ping is working on your phone?

**Comment by amroshahbari27** [comment]
I tried pinging with Termux , works like charm...

**Comment by point-source** [comment]
Just confirmed working using the example code here: https://github.com/point-source/dart_ping/tree/main/dart_ping_ios/example

Can you try running that? Also maybe increase the timeout to a very large value and see if there's just massive latency for some reason. What device / android version are you on?

**Comment by amroshahbari27** [comment]
Yes it works on real device , but not on emulator , THANK YOU  ! 
I managed to work on real device , thank you:)

**Comment by point-source** [comment]
Glad to hear! Closing the issue for now. Lmk if anything else comes up.
