### ISSUE TITLE
In Windows release, you cannot use

### ISSUE THREAD

**Issue by ZhangZhengzz** [point-source/dart_ping#16]
In Windows release, you cannot use

**Comment by point-source** [comment]
Gonna need a lot more information than that.

What version of windows? What version of dart_ping? What type of ping are you trying to run? Can you share a snippet of your code? Are you using this in pure dart or as part of a flutter app? What error are you getting when you try it?

Everyone's environment is different and this has big impacts on how things work. I can't read your mind or predict your environment. Please be more detailed about your reports. It goes a long way. Thanks

**Comment by ZhangZhengzz** [comment]
dart_ping: ^6.1.1
window10
I tried to open exe from a local file, then a doc command window appeared, and then I couldn't get Ping data. But I don't think this will happen when Android studio runs windows. Other devices have no problems in the debug or release versions, but there will be problems in the windows release or manually clicking the generated exe.

**Comment by ZhangZhengzz** [comment]
It is easy to open through the compilation tool, but if you manually open the generated exe, the doc command will appear and the data cannot be obtained. I created a stand-alone flutter application

**Comment by ZhangZhengzz** [comment]
It is easy to open through the compilation tool, but if you manually open the generated exe, the doc command will appear and the data cannot be obtained. I created a stand-alone flutter application

**Comment by ZhangZhengzz** [comment]
![6e8dddb5db24252c3ba371a041663fb](https://user-images.githubusercontent.com/16114352/134612754-48670d23-94fd-4abc-a603-f77ab316384a.png)
![Uploading 193139f2438ad26b7f5fbf1bcc8cb60.png…]()

**Comment by ZhangZhengzz** [comment]
![Uploading 193139f2438ad26b7f5fbf1bcc8cb60.png…]()

**Comment by ZhangZhengzz** [comment]
![193139f2438ad26b7f5fbf1bcc8cb60](https://user-images.githubusercontent.com/16114352/134613083-fb1bd114-f724-4af4-b371-3a84bacee9e3.png)

**Comment by point-source** [comment]
Thanks for the additional context. I will test this locally and get back to you

**Comment by Vonarian** [comment]
@point-source any update? I can't release the app :(

**Comment by boganiLuca** [comment]
This seems to be an issue with Flutter itself more than a package problem: I found different issues in github that speak of this. 
I followed the advice [here](https://github.com/dart-lang/sdk/issues/39945#issuecomment-870428151) and it solved the problem for me, so maybe it can help you too @Vonarian

**Comment by Vonarian** [comment]
@boganiLuca Sorry I didn't update my comment.
I already have solved my issue with that fix to main.cpp :D
Thanks.
