### ISSUE TITLE
Doesn't work when default/global system language is non-english

### ISSUE THREAD

**Issue by point-source** [point-source/dart_ping#2]
Doesn't work for desktop flutter on Windows and Dart native application. It returns no results when running the sample code on these platforms.

![ezgif-1-524ec8190941](https://user-images.githubusercontent.com/23001470/109382055-5b9caf00-78de-11eb-88a8-08578163c27c.gif)

The string "******" is printed in the GIF and no ping results.

_Originally posted by @patricknicolosi in https://github.com/point-source/dart_ping/issues/1#issuecomment-787036256_

**Comment by point-source** [comment]
I have identified the cause and a fix will be published this week

**Comment by patricknicolosi** [comment]
Doesn't work for Dart native application with the latest version (2.0.3)

![video](https://user-images.githubusercontent.com/23001470/109618597-0360e980-7b38-11eb-9f51-865cac1bde3c.gif)

**Comment by point-source** [comment]
You need your main function to be async or it will complete and exit the program before the stream has a chance to receive anything.

**Comment by patricknicolosi** [comment]
`import 'package:dart_ping/dart_ping.dart';

void main() async {
  var ping = Ping(
    'google.com',
    count: 3,
    timeout: 1,
    interval: 1,
    ipv6: false,
  );
  ping.stream.listen((event) {
    print(event);
  });
}`

Even so, no result

**Comment by point-source** [comment]
Having a hard time reproducing. I'm going to reopen this issue for now. I just tested it again myself. Native dart on windows 10:

![image](https://user-images.githubusercontent.com/47544779/109732645-6a02f900-7b72-11eb-940a-e0e76cb0ed59.png)

Can you tell me a bit more about your platform? What version of dart? What version of windows? Thanks

**Comment by patricknicolosi** [comment]
In the pubspec.lock file, the package version is 2.0.3. 

**System info**
Edizione	Windows 10 Pro
Versione	20H2
Data installazione:	‎14/‎01/‎2021
Build sistema operativo	19042.804
Esperienza	Windows Feature Experience Pack 120.2212.551.0

**dart version**
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"

**Comment by patricknicolosi** [comment]
Bug Found! The problem is in the Windows 10 language. The package currently only supports English. The problem is probably in windows_ping.dart in instructions like "data.contains ('Reply from')" or "RegExp (r'Sent = (\ d +), Received = (\ d +), Lost = (\ d +) ') ". Translating these strings into the instructions in italian or changing the language of the system, the problem is solved.

**Comment by point-source** [comment]
Ohhh yeah that makes a lot of sense. If you don't mind posting the equivalent strings for the Italian version, I will happily add Italian support. Thanks for the catch!

**Comment by patricknicolosi** [comment]
Here are the Italian strings. With these new strings the ping is calculated but there is an error in the PingSummary with this language. 

<h2>Equivalent strings in windows_ping.dart</h2>

```
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:async/async.dart';
import 'package:dart_ping/dart_ping.dart';
import 'package:dart_ping/src/ping/base_ping.dart';
import 'package:dart_ping/src/dart_ping_base.dart';

class PingWindows extends BasePing implements Ping {
  PingWindows(
      String host, int count, double interval, double timeout, bool ipv6)
      : super(host, count, interval, timeout, ipv6);

  static final _resRegex =
      RegExp(r'da (.*): byte=(\d+) durata=(\d+.?\d+)ms TTL=(\d+)');
  static final _summaryRegexes = [
    RegExp(r'Trasmessi = (\d+), Ricevuti = (\d+), Persi = (\d+)'),
    RegExp(r'Minimo = (\d+)ms, Massimo = (\d+)ms, Medio = (\d+)ms'),
  ];

  Process _process;

  @override
  Future<void> onListen() async {
    if (_process != null) {
      throw Exception('ping is already running');
    }
    if (ipv6) throw UnimplementedError('IPv6 not implemented for windows');
    var params = [];
    if (count == null) {
      params.add('-t');
    } else {
      params.add('-n');
      params.add(count.toString());
    }
    if (timeout != null) {
      params.add('-w');
      params.add(timeout.toString());
    }
    _process = await Process.start('ping', [...params, host]);
    // ignore: unawaited_futures
    _process.exitCode.then((value) {
      controller.close();
    });
    subscription = StreamGroup.merge([_process.stderr, _process.stdout])
        .transform(utf8.decoder)
        .transform(LineSplitter())
        .transform<PingData>(_windowsTransformer)
        .listen(controller.add);
  }

  @override
  void stop() {
    _process?.kill(ProcessSignal.sigint);
    _process = null;
  }

  /// StreamTransformer for Android response from process stdout/stderr.
  static final StreamTransformer<String, PingData> _windowsTransformer =
      StreamTransformer.fromHandlers(
    handleData: (data, sink) {
      if (data.contains('Risposta da')) {
        if (data.contains('destinazione non raggiungibile')) {
          sink.add(
            PingData(
              error: PingError.RequestTimedOut,
            ),
          );
        }
        final match = _resRegex.firstMatch(data);
        if (match == null) {
          return;
        }
        sink.add(
          PingData(
            response: PingResponse(
              ip: match.group(1),
              ttl: int.parse(match.group(4)),
              time: Duration(
                  microseconds:
                      ((double.parse(match.group(3))) * 1000).floor()),
            ),
          ),
        );
      }
      if (data.contains('Impossibile trovare')) {
        sink.add(
          PingData(
            error: PingError.UnknownHost,
          ),
        );
      }
      if (data.contains('Richiesta scaduta')) {
        sink.add(
          PingData(
            error: PingError.Unknown,
          ),
        );
      }
      if (data.contains('timed out')) {
        sink.add(
          PingData(
            error: PingError.RequestTimedOut,
          ),
        );
      }
      if (data.contains('Persi')) {
        print("-------------> ERROR <--------------");

        final match = _summaryRegexes[0].firstMatch(data);
        final transmitted = match.group(1);
        final received = match.group(2);
        if (transmitted == null || received == null) {
          return;
        }
        sink.add(
          PingData(
            summary: PingSummary(
              transmitted: int.parse(transmitted),
              received: int.parse(received),
            ),
          ),
        );
      }
    },
  );
}

```


<h2>Little problem with Italian</h2>
Program output with translation (Ping is calculated but no PingSummary).
```
PingData(response:PingResponse(seq:null, ip:216.58.198.46, ttl:111, time:41.0 ms), summary:null, error:null)
PingData(response:PingResponse(seq:null, ip:216.58.198.46, ttl:111, time:75.0 ms), summary:null, error:null)
-------------> ERROR <--------------
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)
```

<h2>The reason for the error</h2>
The problem is generated because by pinging in English in Windows the output is the following:

![modificata](https://user-images.githubusercontent.com/23001470/109946215-478af000-7cd8-11eb-8a43-02faf88be87b.png)

Pinging in Italian in Windows the output is:
![d](https://user-images.githubusercontent.com/23001470/109946746-ddbf1600-7cd8-11eb-8e70-e798c0ade089.PNG)


The problem is in the following statement where the word "Persi" must be preceded by some command to go to new line.
```
 static final _summaryRegexes = [
    RegExp(r'Trasmessi = (\d+), Ricevuti = (\d+), Persi = (\d+)'),
    RegExp(r'Minimo = (\d+)ms, Massimo = (\d+)ms, Medio = (\d+)ms'),
  ];
```

**Comment by point-source** [comment]
@patricknicolosi  Version 5.3.0 now allows you to override the parsing regex strings with a PingParser object. You can also individually set strings after Ping() has been initialized. This should allow you to support any language as long as you can write an appropriate regex for the output. Let me know if that helps.

Also related to issue #9

**Comment by point-source** [comment]
As of version 5.4.2, both the parser and the character decoding may be overridden. This should allow sufficient compatibility with non-English platforms. Documentation for how to do this is now in the readme. Closing this issue for now.
