### ISSUE TITLE
Flutter icmp ping made breaking changes to their Enum types

### ISSUE THREAD

**Issue by NZhlebinkov** [point-source/dart_ping#23]
In the file `dart_ping_ios.dart` in VS Code. From there change lines 53 and 56 to be the following: `case fp.PingError.requestTimedOut:` and `case fp.PingError.unknownHost:`. Note the difference in capitalization of the enum types

**Comment by webluoye** [comment]
same error

**Comment by hqt98** [comment]
Same error for me
