### ISSUE TITLE
macOS no working

### ISSUE THREAD

**Issue by szxv587** [point-source/dart_ping#24]
The macos (ping.stream.listen) API often has no data callback, and a few times there is a data callback

**Comment by szxv587** [comment]
xcode release build has no data call back

**Comment by point-source** [comment]
I will try to reproduce. Thanks for the report. Please ensure you have the network permission granted in your info.plist.

**Comment by szxv587** [comment]
Network permissions have been granted, I tried to ping using the [process_run](https://pub.dev/packages/process_run) plugin and found the same error message (ping: recvmsg: Operation not permitted), the plugin mentioned, If you want to run executable in a MacOS flutter context, you need to disable sandbox mode. This does solve my problem, but it keeps my app off the app store

**Comment by point-source** [comment]
I was able to reproduce and seemingly solve the issue by ensuring both of these network entitlements are set:

```
<key>com.apple.security.network.server</key>
<true/>
<key>com.apple.security.network.client</key>
<true/>
```

This appeared to work on macOS in release mode with sandbox enabled and no changes made to dart_ping on the latest version (7.0.0).

If this solves your issue, let me know and I'll add it to the documentation. Thanks

**Comment by szxv587** [comment]
In sandbox mode, it is really necessary to add these two network permissions to work, this solved my problem

**Comment by point-source** [comment]
Documentation has been updated. Thanks
