### ISSUE TITLE
Web Platform

### ISSUE THREAD

**Issue by sys-wanto** [point-source/dart_ping#44]
Can you make this support for Web?
![image](https://user-images.githubusercontent.com/19337495/216761090-43a839b6-9648-426c-8183-8d6230ada6b1.png)

**Comment by point-source** [comment]
Unfortunately, this is not possible due to the reasons outlined [here](https://github.com/point-source/dart_ping/pull/41#issuecomment-1399668801) and [here](https://github.com/point-source/dart_ping/issues/15#issuecomment-920350499).
