### ISSUE TITLE
【Windows】FormatException: Missing extension byte (at offset 3)

### ISSUE THREAD

**Issue by LambGe** [point-source/dart_ping#65]
final ping = Ping('google.com', count: 5);

    // [Optional]
    // Preview command that will be run (helpful for debugging)
    print('Running command: ${ping.command}');

    // Begin ping process and listen for output
    ping.stream.listen((event) {
      print(event.toString());
    });

flutter: │ FormatException: Missing extension byte (at offset 3)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1956:7)
flutter: │ #1   _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
flutter: │ #2   _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
flutter: │ #3   _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
flutter: │ #4   _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
flutter: │ #5   _rootRunUnary (dart:async/zone.dart:1407:47)
flutter: │ #6   _CustomZone.runUnary (dart:async/zone.dart:1308:19)
flutter: │ #7   _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
flutter:

**Comment by zmaplex** [comment]
try:
```dart
Ping('google.com', count: 5, forceCodepage: true);
```

```
    /// Force the console process to use codepage 437 (DOS Latin US)
    ///
    /// Under the hood, this appends the ping command with the `chcp` command
    /// like so: `chcp 437 && ping {opts}`
    bool forceCodepage = false,
```

**Comment by point-source** [comment]
@LambGe Sorry I didn't see this earlier. @zmaplex is correct, try forcing the codepage first. If that still does not work, can you let me know what default language is configured on your OS?

**Comment by LambGe** [comment]
Thank you, it can work normally now.
