### ISSUE TITLE
How can I use multiple concurrent Ping instances without blocking the main thread?

### ISSUE THREAD

**Issue by nicolasvahidzein** [point-source/dart_ping#8]
This is not a bug but more of a practical question.

When i run a process using your package, is it locking up my application? I mean this in the sense that if it's on the same thread the time it takes to finish my list of domains to ping it will block my app from processing other actions. Is this a fair assumption?

**Comment by point-source** [comment]
It is non-blocking in as much as listening to a typical stream would be. There are many ways to do concurrent pings depending on how many times you want to ping each domain. I've been able to simultaneously ping 255 IPs at once, non-blocking with this library. I don't recommend doing that many, but it is possible. If you tell me what your ideal behavior would be, I can give you some basic example code to do that.

Underneath the library, each Ping().stream.listen() instance spawns a ping process on the host OS. This is separate from your dart application and could be on a separate thread or core depending on what the host OS does with it.

**Comment by nicolasvahidzein** [comment]
Thank you for your response. I was asking that in the event that it was blocking the app from it's startup process because i use this later on to determine which CDN to use based on the response time.
